repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        always_run: true
    -   id: check-ast
        always_run: true
    -   id: end-of-file-fixer
        always_run: true
    -   id: check-executables-have-shebangs
        always_run: true
    -   id: check-merge-conflict
        always_run: true
    -   id: debug-statements
        always_run: true
    -   id: fix-encoding-pragma
        always_run: true
    -   id: requirements-txt-fixer
        always_run: true

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        always_run: true

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        exclude: ^tests/
        args: ["."]
        always_run: true
